### ISSUE TITLE
gRPC error after END_OF_UTTERANCE

### ISSUE THREAD

**Issue by championswimmer** [androidthings/sample-googleassistant#42] opened 2017-09-21 20:22 UTC
Here's the error - 

```

09-21 20:04:29.944 2165-2293/com.example.androidthings.assistant D/AssistantActivity: converse response event: END_OF_UTTERANCE
09-21 20:04:31.151 2165-2175/com.example.androidthings.assistant I/zygote: Waiting for a blocking GC ObjectsAllocated
09-21 20:04:31.187 2165-2175/com.example.androidthings.assistant I/zygote: Waiting for a blocking GC ObjectsAllocated
09-21 20:04:31.187 2165-2175/com.example.androidthings.assistant I/zygote: WaitForGcToComplete blocked for 36.391ms for cause ObjectsAllocated
09-21 20:04:46.733 2165-2173/com.example.androidthings.assistant I/zygote: Do partial code cache collection, code=62KB, data=58KB
09-21 20:04:46.735 2165-2173/com.example.androidthings.assistant I/zygote: After code cache collection, code=62KB, data=58KB
09-21 20:04:46.735 2165-2173/com.example.androidthings.assistant I/zygote: Increasing code cache capacity to 256KB
09-21 20:05:29.866 2165-2293/com.example.androidthings.assistant E/AssistantActivity: converse error:
                                                                                      io.grpc.StatusRuntimeException: INTERNAL: Received unexpected EOS on DATA frame from server.
                                                                                          at io.grpc.Status.asRuntimeException(Status.java:540)
                                                                                          at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:392)
                                                                                          at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:428)
                                                                                          at io.grpc.internal.ClientCallImpl.access$100(ClientCallImpl.java:76)
                                                                                          at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:514)
                                                                                          at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:431)
                                                                                          at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:546)
                                                                                          at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
                                                                                          at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:152)
                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                                          at java.lang.Thread.run(Thread.java:764)
```

I get it after I've spoken and then become quiet (it understands END_OF_UTTERANCE), then starts uploading the speech to Googel Cloud ( I can see in network monitor), and it then shows this stacktrace. App doesn't crash, but it stops working after this point

**Comment by championswimmer** [comment] 2017-09-21 20:22
Tried this on a PICO and a Raspberry Pi 3

**Comment by Fleker** [comment] 2017-09-21 22:51
Duplicate of #32

**Closed by Fleker** 2017-09-21 22:51 UTC
